Ratings and reviews file upload basic function for single files
Idakka/Project-Atelier pull request #32
Opened 2021-06-05 07:41 UTC by NylonEric

* Added buttons and click handlers for file upload

* Added port to react client component for axios requests

* Changed static port to dynamically read from window.location

* 8 Added a temporary server route for /upload POST request

* Fixed missing semicolons

* Added rendering tests for star-review and ratings-main

2021-06-05 20:27 UTC, milofultz approved these changes

2021-06-05 20:27 UTC, milofultz commented on client/src/components/product_detail_page.jsx
> +import Axios from 'axios';
don't know if we should keep it lowercase but that's how I've always seen it done

2021-06-05 20:27 UTC, milofultz commented on client/src/components/product_detail_page.jsx
> +    Axios.post(`http://localhost:${port}/upload`, data, {
you don't need an empty object if you don't have any headers or anything. I know this is a proof of concept, so don't know if it's worth dealing with since it will be deleted

2021-06-06 13:38 UTC, milofultz requested changes
Just the lowercase axios thing so we can keep consistency

2021-06-07 05:09 UTC, NylonEric commented
Changed the axios import to be lowercase for consistency.

2021-06-07 05:09 UTC, merged